/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

/**
 *
 * @author Gabriel
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        menuArchivoClientes = new javax.swing.JMenuItem();
        menuArchivoProductos = new javax.swing.JMenuItem();
        menuArchivoUsuarios = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuArchivoCambioClave = new javax.swing.JMenuItem();
        menuArchivoCambioUsuario = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuArchivoSalir = new javax.swing.JMenuItem();
        mnuMovimientos = new javax.swing.JMenu();
        menuMovimientosNuevaFactura = new javax.swing.JMenuItem();
        menuMovimientosReporteFactura = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        menuAyudaAcercaDe = new javax.swing.JMenuItem();
        menuAyudaAyuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Facturación");

        mnuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/folder.png"))); // NOI18N
        mnuArchivo.setText("Archivo");

        menuArchivoClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_orange.png"))); // NOI18N
        menuArchivoClientes.setText("Clientes");
        mnuArchivo.add(menuArchivoClientes);

        menuArchivoProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/package.png"))); // NOI18N
        menuArchivoProductos.setText("Productos");
        mnuArchivo.add(menuArchivoProductos);

        menuArchivoUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group.png"))); // NOI18N
        menuArchivoUsuarios.setText("Usuarios");
        mnuArchivo.add(menuArchivoUsuarios);
        mnuArchivo.add(jSeparator1);

        menuArchivoCambioClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/key.png"))); // NOI18N
        menuArchivoCambioClave.setText("Cambio clave");
        menuArchivoCambioClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArchivoCambioClaveActionPerformed(evt);
            }
        });
        mnuArchivo.add(menuArchivoCambioClave);

        menuArchivoCambioUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        menuArchivoCambioUsuario.setText("Cambio usuario");
        mnuArchivo.add(menuArchivoCambioUsuario);
        mnuArchivo.add(jSeparator2);

        menuArchivoSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door_out.png"))); // NOI18N
        menuArchivoSalir.setText("Salir");
        mnuArchivo.add(menuArchivoSalir);

        jMenuBar1.add(mnuArchivo);

        mnuMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        mnuMovimientos.setText("Movimientos");

        menuMovimientosNuevaFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/documento.png"))); // NOI18N
        menuMovimientosNuevaFactura.setText("Nueva Factura");
        mnuMovimientos.add(menuMovimientosNuevaFactura);

        menuMovimientosReporteFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report.png"))); // NOI18N
        menuMovimientosReporteFactura.setText("Reporte Facturas");
        mnuMovimientos.add(menuMovimientosReporteFactura);

        jMenuBar1.add(mnuMovimientos);

        mnuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.png"))); // NOI18N
        mnuAyuda.setText("Ayuda");

        menuAyudaAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/application_edit.png"))); // NOI18N
        menuAyudaAcercaDe.setText("Acerca de");
        mnuAyuda.add(menuAyudaAcercaDe);

        menuAyudaAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.png"))); // NOI18N
        menuAyudaAyuda.setText("Ayuda");
        mnuAyuda.add(menuAyudaAyuda);

        jMenuBar1.add(mnuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuArchivoCambioClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArchivoCambioClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuArchivoCambioClaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem menuArchivoCambioClave;
    private javax.swing.JMenuItem menuArchivoCambioUsuario;
    private javax.swing.JMenuItem menuArchivoClientes;
    private javax.swing.JMenuItem menuArchivoProductos;
    private javax.swing.JMenuItem menuArchivoSalir;
    private javax.swing.JMenuItem menuArchivoUsuarios;
    private javax.swing.JMenuItem menuAyudaAcercaDe;
    private javax.swing.JMenuItem menuAyudaAyuda;
    private javax.swing.JMenuItem menuMovimientosNuevaFactura;
    private javax.swing.JMenuItem menuMovimientosReporteFactura;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenu mnuMovimientos;
    // End of variables declaration//GEN-END:variables
}
